// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recognition.proto

#include "recognition.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace cniface {
constexpr ExtractFeatureRequest::ExtractFeatureRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : kps_()
  , faceimagebase64_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct ExtractFeatureRequestDefaultTypeInternal {
  constexpr ExtractFeatureRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExtractFeatureRequestDefaultTypeInternal() {}
  union {
    ExtractFeatureRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExtractFeatureRequestDefaultTypeInternal _ExtractFeatureRequest_default_instance_;
constexpr ExtractFeatureResponse::ExtractFeatureResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : message_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , featurebase64_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , code_(int64_t{0}){}
struct ExtractFeatureResponseDefaultTypeInternal {
  constexpr ExtractFeatureResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExtractFeatureResponseDefaultTypeInternal() {}
  union {
    ExtractFeatureResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExtractFeatureResponseDefaultTypeInternal _ExtractFeatureResponse_default_instance_;
constexpr SimilarityRequest::SimilarityRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : featurebase64_1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , featurebase64_2_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SimilarityRequestDefaultTypeInternal {
  constexpr SimilarityRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SimilarityRequestDefaultTypeInternal() {}
  union {
    SimilarityRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SimilarityRequestDefaultTypeInternal _SimilarityRequest_default_instance_;
constexpr SimilarityeResponse::SimilarityeResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : message_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , code_(int64_t{0})
  , similarity_(0){}
struct SimilarityeResponseDefaultTypeInternal {
  constexpr SimilarityeResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SimilarityeResponseDefaultTypeInternal() {}
  union {
    SimilarityeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SimilarityeResponseDefaultTypeInternal _SimilarityeResponse_default_instance_;
}  // namespace cniface
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_recognition_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_recognition_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_recognition_2eproto = nullptr;

const uint32_t TableStruct_recognition_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureRequest, faceimagebase64_),
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureRequest, kps_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureResponse, code_),
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureResponse, message_),
  PROTOBUF_FIELD_OFFSET(::cniface::ExtractFeatureResponse, featurebase64_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityRequest, featurebase64_1_),
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityRequest, featurebase64_2_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityeResponse, code_),
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityeResponse, message_),
  PROTOBUF_FIELD_OFFSET(::cniface::SimilarityeResponse, similarity_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cniface::ExtractFeatureRequest)},
  { 8, -1, -1, sizeof(::cniface::ExtractFeatureResponse)},
  { 17, -1, -1, sizeof(::cniface::SimilarityRequest)},
  { 25, -1, -1, sizeof(::cniface::SimilarityeResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cniface::_ExtractFeatureRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cniface::_ExtractFeatureResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cniface::_SimilarityRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cniface::_SimilarityeResponse_default_instance_),
};

const char descriptor_table_protodef_recognition_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021recognition.proto\022\007cniface\"=\n\025ExtractF"
  "eatureRequest\022\027\n\017faceImageBase64\030\001 \001(\t\022\013"
  "\n\003kps\030\002 \003(\002\"N\n\026ExtractFeatureResponse\022\014\n"
  "\004code\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\022\025\n\rfeatureB"
  "ase64\030\003 \001(\t\"E\n\021SimilarityRequest\022\027\n\017feat"
  "ureBase64_1\030\001 \001(\t\022\027\n\017featureBase64_2\030\002 \001"
  "(\t\"H\n\023SimilarityeResponse\022\014\n\004code\030\001 \001(\003\022"
  "\017\n\007message\030\002 \001(\t\022\022\n\nsimilarity\030\003 \001(\0022\263\001\n"
  "\022RecognitionService\022S\n\016extractFeature\022\036."
  "cniface.ExtractFeatureRequest\032\037.cniface."
  "ExtractFeatureResponse\"\000\022H\n\nsimilarity\022\032"
  ".cniface.SimilarityRequest\032\034.cniface.Sim"
  "ilarityeResponse\"\000BC\n#cn.abellee.cniface"
  ".grpc.recognitionB\020RecognitionProtoP\001\242\002\007"
  "CNIFACEb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_recognition_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_recognition_2eproto = {
  false, false, 575, descriptor_table_protodef_recognition_2eproto, "recognition.proto", 
  &descriptor_table_recognition_2eproto_once, nullptr, 0, 4,
  schemas, file_default_instances, TableStruct_recognition_2eproto::offsets,
  file_level_metadata_recognition_2eproto, file_level_enum_descriptors_recognition_2eproto, file_level_service_descriptors_recognition_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_recognition_2eproto_getter() {
  return &descriptor_table_recognition_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_recognition_2eproto(&descriptor_table_recognition_2eproto);
namespace cniface {

// ===================================================================

class ExtractFeatureRequest::_Internal {
 public:
};

ExtractFeatureRequest::ExtractFeatureRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  kps_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cniface.ExtractFeatureRequest)
}
ExtractFeatureRequest::ExtractFeatureRequest(const ExtractFeatureRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      kps_(from.kps_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  faceimagebase64_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    faceimagebase64_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_faceimagebase64().empty()) {
    faceimagebase64_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_faceimagebase64(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:cniface.ExtractFeatureRequest)
}

inline void ExtractFeatureRequest::SharedCtor() {
faceimagebase64_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  faceimagebase64_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ExtractFeatureRequest::~ExtractFeatureRequest() {
  // @@protoc_insertion_point(destructor:cniface.ExtractFeatureRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ExtractFeatureRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  faceimagebase64_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ExtractFeatureRequest::ArenaDtor(void* object) {
  ExtractFeatureRequest* _this = reinterpret_cast< ExtractFeatureRequest* >(object);
  (void)_this;
}
void ExtractFeatureRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExtractFeatureRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ExtractFeatureRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:cniface.ExtractFeatureRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  kps_.Clear();
  faceimagebase64_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExtractFeatureRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string faceImageBase64 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_faceimagebase64();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cniface.ExtractFeatureRequest.faceImageBase64"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float kps = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kps(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 21) {
          _internal_add_kps(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ExtractFeatureRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cniface.ExtractFeatureRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string faceImageBase64 = 1;
  if (!this->_internal_faceimagebase64().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_faceimagebase64().data(), static_cast<int>(this->_internal_faceimagebase64().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cniface.ExtractFeatureRequest.faceImageBase64");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_faceimagebase64(), target);
  }

  // repeated float kps = 2;
  if (this->_internal_kps_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_kps(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cniface.ExtractFeatureRequest)
  return target;
}

size_t ExtractFeatureRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cniface.ExtractFeatureRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float kps = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kps_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string faceImageBase64 = 1;
  if (!this->_internal_faceimagebase64().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_faceimagebase64());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExtractFeatureRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ExtractFeatureRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExtractFeatureRequest::GetClassData() const { return &_class_data_; }

void ExtractFeatureRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ExtractFeatureRequest *>(to)->MergeFrom(
      static_cast<const ExtractFeatureRequest &>(from));
}


void ExtractFeatureRequest::MergeFrom(const ExtractFeatureRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cniface.ExtractFeatureRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  kps_.MergeFrom(from.kps_);
  if (!from._internal_faceimagebase64().empty()) {
    _internal_set_faceimagebase64(from._internal_faceimagebase64());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExtractFeatureRequest::CopyFrom(const ExtractFeatureRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cniface.ExtractFeatureRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExtractFeatureRequest::IsInitialized() const {
  return true;
}

void ExtractFeatureRequest::InternalSwap(ExtractFeatureRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  kps_.InternalSwap(&other->kps_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &faceimagebase64_, lhs_arena,
      &other->faceimagebase64_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ExtractFeatureRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_recognition_2eproto_getter, &descriptor_table_recognition_2eproto_once,
      file_level_metadata_recognition_2eproto[0]);
}

// ===================================================================

class ExtractFeatureResponse::_Internal {
 public:
};

ExtractFeatureResponse::ExtractFeatureResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cniface.ExtractFeatureResponse)
}
ExtractFeatureResponse::ExtractFeatureResponse(const ExtractFeatureResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_message(), 
      GetArenaForAllocation());
  }
  featurebase64_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    featurebase64_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_featurebase64().empty()) {
    featurebase64_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_featurebase64(), 
      GetArenaForAllocation());
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:cniface.ExtractFeatureResponse)
}

inline void ExtractFeatureResponse::SharedCtor() {
message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
featurebase64_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  featurebase64_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
code_ = int64_t{0};
}

ExtractFeatureResponse::~ExtractFeatureResponse() {
  // @@protoc_insertion_point(destructor:cniface.ExtractFeatureResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ExtractFeatureResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  featurebase64_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ExtractFeatureResponse::ArenaDtor(void* object) {
  ExtractFeatureResponse* _this = reinterpret_cast< ExtractFeatureResponse* >(object);
  (void)_this;
}
void ExtractFeatureResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExtractFeatureResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ExtractFeatureResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:cniface.ExtractFeatureResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty();
  featurebase64_.ClearToEmpty();
  code_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExtractFeatureResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cniface.ExtractFeatureResponse.message"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string featureBase64 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_featurebase64();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cniface.ExtractFeatureResponse.featureBase64"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ExtractFeatureResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cniface.ExtractFeatureResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cniface.ExtractFeatureResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // string featureBase64 = 3;
  if (!this->_internal_featurebase64().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_featurebase64().data(), static_cast<int>(this->_internal_featurebase64().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cniface.ExtractFeatureResponse.featureBase64");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_featurebase64(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cniface.ExtractFeatureResponse)
  return target;
}

size_t ExtractFeatureResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cniface.ExtractFeatureResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // string featureBase64 = 3;
  if (!this->_internal_featurebase64().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_featurebase64());
  }

  // int64 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExtractFeatureResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ExtractFeatureResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExtractFeatureResponse::GetClassData() const { return &_class_data_; }

void ExtractFeatureResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ExtractFeatureResponse *>(to)->MergeFrom(
      static_cast<const ExtractFeatureResponse &>(from));
}


void ExtractFeatureResponse::MergeFrom(const ExtractFeatureResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cniface.ExtractFeatureResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _internal_set_message(from._internal_message());
  }
  if (!from._internal_featurebase64().empty()) {
    _internal_set_featurebase64(from._internal_featurebase64());
  }
  if (from._internal_code() != 0) {
    _internal_set_code(from._internal_code());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExtractFeatureResponse::CopyFrom(const ExtractFeatureResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cniface.ExtractFeatureResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExtractFeatureResponse::IsInitialized() const {
  return true;
}

void ExtractFeatureResponse::InternalSwap(ExtractFeatureResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &message_, lhs_arena,
      &other->message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &featurebase64_, lhs_arena,
      &other->featurebase64_, rhs_arena
  );
  swap(code_, other->code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ExtractFeatureResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_recognition_2eproto_getter, &descriptor_table_recognition_2eproto_once,
      file_level_metadata_recognition_2eproto[1]);
}

// ===================================================================

class SimilarityRequest::_Internal {
 public:
};

SimilarityRequest::SimilarityRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cniface.SimilarityRequest)
}
SimilarityRequest::SimilarityRequest(const SimilarityRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  featurebase64_1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    featurebase64_1_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_featurebase64_1().empty()) {
    featurebase64_1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_featurebase64_1(), 
      GetArenaForAllocation());
  }
  featurebase64_2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    featurebase64_2_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_featurebase64_2().empty()) {
    featurebase64_2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_featurebase64_2(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:cniface.SimilarityRequest)
}

inline void SimilarityRequest::SharedCtor() {
featurebase64_1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  featurebase64_1_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
featurebase64_2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  featurebase64_2_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SimilarityRequest::~SimilarityRequest() {
  // @@protoc_insertion_point(destructor:cniface.SimilarityRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SimilarityRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  featurebase64_1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  featurebase64_2_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SimilarityRequest::ArenaDtor(void* object) {
  SimilarityRequest* _this = reinterpret_cast< SimilarityRequest* >(object);
  (void)_this;
}
void SimilarityRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SimilarityRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SimilarityRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:cniface.SimilarityRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  featurebase64_1_.ClearToEmpty();
  featurebase64_2_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimilarityRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string featureBase64_1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_featurebase64_1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cniface.SimilarityRequest.featureBase64_1"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string featureBase64_2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_featurebase64_2();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cniface.SimilarityRequest.featureBase64_2"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimilarityRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cniface.SimilarityRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string featureBase64_1 = 1;
  if (!this->_internal_featurebase64_1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_featurebase64_1().data(), static_cast<int>(this->_internal_featurebase64_1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cniface.SimilarityRequest.featureBase64_1");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_featurebase64_1(), target);
  }

  // string featureBase64_2 = 2;
  if (!this->_internal_featurebase64_2().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_featurebase64_2().data(), static_cast<int>(this->_internal_featurebase64_2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cniface.SimilarityRequest.featureBase64_2");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_featurebase64_2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cniface.SimilarityRequest)
  return target;
}

size_t SimilarityRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cniface.SimilarityRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string featureBase64_1 = 1;
  if (!this->_internal_featurebase64_1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_featurebase64_1());
  }

  // string featureBase64_2 = 2;
  if (!this->_internal_featurebase64_2().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_featurebase64_2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimilarityRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SimilarityRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimilarityRequest::GetClassData() const { return &_class_data_; }

void SimilarityRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SimilarityRequest *>(to)->MergeFrom(
      static_cast<const SimilarityRequest &>(from));
}


void SimilarityRequest::MergeFrom(const SimilarityRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cniface.SimilarityRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_featurebase64_1().empty()) {
    _internal_set_featurebase64_1(from._internal_featurebase64_1());
  }
  if (!from._internal_featurebase64_2().empty()) {
    _internal_set_featurebase64_2(from._internal_featurebase64_2());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimilarityRequest::CopyFrom(const SimilarityRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cniface.SimilarityRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimilarityRequest::IsInitialized() const {
  return true;
}

void SimilarityRequest::InternalSwap(SimilarityRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &featurebase64_1_, lhs_arena,
      &other->featurebase64_1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &featurebase64_2_, lhs_arena,
      &other->featurebase64_2_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SimilarityRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_recognition_2eproto_getter, &descriptor_table_recognition_2eproto_once,
      file_level_metadata_recognition_2eproto[2]);
}

// ===================================================================

class SimilarityeResponse::_Internal {
 public:
};

SimilarityeResponse::SimilarityeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cniface.SimilarityeResponse)
}
SimilarityeResponse::SimilarityeResponse(const SimilarityeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_message(), 
      GetArenaForAllocation());
  }
  ::memcpy(&code_, &from.code_,
    static_cast<size_t>(reinterpret_cast<char*>(&similarity_) -
    reinterpret_cast<char*>(&code_)) + sizeof(similarity_));
  // @@protoc_insertion_point(copy_constructor:cniface.SimilarityeResponse)
}

inline void SimilarityeResponse::SharedCtor() {
message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&code_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&similarity_) -
    reinterpret_cast<char*>(&code_)) + sizeof(similarity_));
}

SimilarityeResponse::~SimilarityeResponse() {
  // @@protoc_insertion_point(destructor:cniface.SimilarityeResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SimilarityeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SimilarityeResponse::ArenaDtor(void* object) {
  SimilarityeResponse* _this = reinterpret_cast< SimilarityeResponse* >(object);
  (void)_this;
}
void SimilarityeResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SimilarityeResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SimilarityeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:cniface.SimilarityeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty();
  ::memset(&code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&similarity_) -
      reinterpret_cast<char*>(&code_)) + sizeof(similarity_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimilarityeResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cniface.SimilarityeResponse.message"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float similarity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          similarity_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimilarityeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cniface.SimilarityeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cniface.SimilarityeResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // float similarity = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_similarity = this->_internal_similarity();
  uint32_t raw_similarity;
  memcpy(&raw_similarity, &tmp_similarity, sizeof(tmp_similarity));
  if (raw_similarity != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_similarity(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cniface.SimilarityeResponse)
  return target;
}

size_t SimilarityeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cniface.SimilarityeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // int64 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_code());
  }

  // float similarity = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_similarity = this->_internal_similarity();
  uint32_t raw_similarity;
  memcpy(&raw_similarity, &tmp_similarity, sizeof(tmp_similarity));
  if (raw_similarity != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimilarityeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SimilarityeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimilarityeResponse::GetClassData() const { return &_class_data_; }

void SimilarityeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SimilarityeResponse *>(to)->MergeFrom(
      static_cast<const SimilarityeResponse &>(from));
}


void SimilarityeResponse::MergeFrom(const SimilarityeResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cniface.SimilarityeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _internal_set_code(from._internal_code());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_similarity = from._internal_similarity();
  uint32_t raw_similarity;
  memcpy(&raw_similarity, &tmp_similarity, sizeof(tmp_similarity));
  if (raw_similarity != 0) {
    _internal_set_similarity(from._internal_similarity());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimilarityeResponse::CopyFrom(const SimilarityeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cniface.SimilarityeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimilarityeResponse::IsInitialized() const {
  return true;
}

void SimilarityeResponse::InternalSwap(SimilarityeResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &message_, lhs_arena,
      &other->message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimilarityeResponse, similarity_)
      + sizeof(SimilarityeResponse::similarity_)
      - PROTOBUF_FIELD_OFFSET(SimilarityeResponse, code_)>(
          reinterpret_cast<char*>(&code_),
          reinterpret_cast<char*>(&other->code_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SimilarityeResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_recognition_2eproto_getter, &descriptor_table_recognition_2eproto_once,
      file_level_metadata_recognition_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace cniface
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cniface::ExtractFeatureRequest* Arena::CreateMaybeMessage< ::cniface::ExtractFeatureRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cniface::ExtractFeatureRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::cniface::ExtractFeatureResponse* Arena::CreateMaybeMessage< ::cniface::ExtractFeatureResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cniface::ExtractFeatureResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::cniface::SimilarityRequest* Arena::CreateMaybeMessage< ::cniface::SimilarityRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cniface::SimilarityRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::cniface::SimilarityeResponse* Arena::CreateMaybeMessage< ::cniface::SimilarityeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cniface::SimilarityeResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
