name: CNIFace CI

on:
  push:
    branches: [main]
    paths:
      - "**"
      - "!**.md"
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!**.md"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REACTUSERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get date time
        id: date
        run: echo "::set-output name=current_time::$(date +'%Y%m%d%H%M')"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REACTUSERNAME }}/cniface:latest
            ${{ secrets.REACTUSERNAME }}/cniface:${{ steps.date.outputs.current_time }}
